

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3"],
		"CDFG" : "fir_optimized",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Aligned", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "3",
		"VariableLatency" : "0", "ExactLatency" : "7", "EstimateLatencyMin" : "7", "EstimateLatencyMax" : "7",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "output_r", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "input_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_45", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_44", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_43", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_42", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_41", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_40", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_39", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_38", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_37", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_36", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_35", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_34", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_33", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_32", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_31", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_30", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_29", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_28", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_27", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_26", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_25", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_24", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_23", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_22", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_21", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_20", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_19", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_18", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_17", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_16", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_15", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_14", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_13", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_12", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_11", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ13fir_optimizedPiiE9shift_reg_10", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "fir_optimized_int_int_shift_reg_9", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "fir_optimized_int_int_shift_reg_8", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "fir_optimized_int_int_shift_reg_7", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "fir_optimized_int_int_shift_reg_6", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "fir_optimized_int_int_shift_reg_5", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "fir_optimized_int_int_shift_reg_4", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "fir_optimized_int_int_shift_reg_3", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "fir_optimized_int_int_shift_reg_2", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "fir_optimized_int_int_shift_reg_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "fir_optimized_int_int_shift_reg", "Type" : "OVld", "Direction" : "IO"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_12s_32_2_1_U1", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_12s_32_2_1_U2", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_11s_32_2_1_U3", "Parent" : "0"}]}
